#pragma once

#define COLOR_BLACK 0
#define COLOR_DARK_BLUE 1
#define COLOR_DARK_GREEN 2
#define COLOR_DARK_CYAN 3
#define COLOR_DARK_RED 4
#define COLOR_DARK_VIOLET 5
#define COLOR_DARK_YELLOW 6
#define COLOR_GREY 7
#define COLOR_DARK_GREY 8
#define COLOR_BLUE 9
#define COLOR_GREEN 10
#define COLOR_CYAN 11
#define COLOR_RED 12
#define COLOR_VIOLET 13
#define COLOR_YELLOW 14
#define COLOR_WHITE 15
